#!/usr/bin/env bash
cd "$(dirname "$0")"/..

PYTHONPATH=`pwd`
PYTHONPATH=$SPARK_HOME/python/:$PYTHONPATH

# Test
#pep8 --first `find yaga -name "*.py"` &&\ -> We don't need all best practices, do we ? XD
python tests/test_handle_geodata.py &&\
python setup.py build
